CREATE TABLE IF NOT EXISTS "ecommerce_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ecommerce_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"visibility" text DEFAULT 'private',
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "ecommerce_category_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "ecommerce_sub_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ecommerce_sub_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"visibility" text DEFAULT 'private',
	"category_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "ecommerce_sub_category_name_unique" UNIQUE("name")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "ecommerce_sub_category" ADD CONSTRAINT "ecommerce_sub_category_category_id_ecommerce_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."ecommerce_category"("id") ON DELETE restrict ON UPDATE restrict;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "category_name_idx" ON "ecommerce_category" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sub_category_name_idx" ON "ecommerce_sub_category" USING btree ("name");