CREATE TABLE "ecommerce_media" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ecommerce_media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"type" text DEFAULT 'image',
	"sources" varchar[] DEFAULT '{}' NOT NULL,
	"visibility" text DEFAULT 'private',
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "ecommerce_media_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE INDEX "media_name_idx" ON "ecommerce_media" USING btree ("name");